name: CI

on:
  pull_request:
  push:
    branches: ["series/2.x"]
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Lint code
        run: sbt scalafmtCheckAll

  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '21']
        scala: ['3.3', '2.13', '2.12']
    env:
      AWS_ACCESS_KEY_ID: dummykey
      AWS_SECRET_ACCESS_KEY: dummykey
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests
        run: sbt -J-XX:+UseG1GC -J-Xmx6g -J-Xms6g -J-Xss16m "++${{ matrix.scala }}; test"
      - name: Run DynamoDBLocal
        run: docker compose -f docker/docker-compose.yml up -d
      - name: Run integration tests
        run: sbt -J-XX:+UseG1GC -J-Xmx6g -J-Xms6g -J-Xss16m "++${{ matrix.scala }}; it:test"

  mdoc:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Setup GPG
        uses: olafurpg/setup-gpg@v3
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check Document Generation
        run: sbt -J-XX:+UseG1GC -J-Xmx6g -J-Xms6g -J-Xss16m docs/compileDocs

  ci:
    runs-on: ubuntu-20.04
    needs: [build, lint, mdoc]
    steps:
      - name: Report successful build
        run: echo "ci passed"

  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - run: sbt -J-XX:+UseG1GC -J-Xmx6g -J-Xms6g -J-Xss16m ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
